[workspace]
authors = ["ZEROYONN <reishi.k0702@gmail.com>"]
channels = ["conda-forge"]
name = "mahjong-score"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
opencv = ">=4.12.0,<5"
python-dotenv = ">=1.1.1,<2"
google-cloud-vision = ">=3.10.2,<4"
gspread = ">=5.12.4,<6"
oauth2client = ">=4.1.3,<5"
loguru = ">=0.7.3,<0.8"
pytest = ">=8.4.1,<9"
gspread-pandas = ">=3.3.0,<4"
hypothesis = ">=6.135.32,<7"
faker = ">=37.4.2,<38"
